version: '3'

services:
  commentserver:
    container_name: comments
    build: .
    depends_on:
      - 'database'
    ports: 
      - '4001:4001'

  mongo-seed:
    build: .
    depends_on: 
      - 'database'
    command: 'npm run seed'

  database:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'